var figure = {
    "frames": [], 
    "layout": {
        "autosize": true, 
        "breakpoints": [], 
        "hovermode": "closest", 
        "xaxis": {
            "range": [
                -0.5, 
                49.5
            ], 
            "type": "category", 
            "autorange": true, 
            "title": "Column 1"
        }, 
        "yaxis": {
            "range": [
                0, 
                7226.315789473684
            ], 
            "type": "linear", 
            "autorange": true, 
            "title": "Column 0"
        }
    }, 
    "data": [
        {
            "autobinx": true, 
            "uid": "a5081c", 
            "ysrc": "aircar:2:8d5841", 
            "xsrc": "aircar:2:e6d4e6", 
            "name": "Column 1", 
            "mode": "markers", 
            "y": [
                "Number of Pet Households (in 1000)", 
                "1,088", 
                "1,497", 
                "716", 
                "6,865", 
                "1,217", 
                "728", 
                "189", 
                "63", 
                "4,138", 
                "2,093", 
                "352", 
                "2,602", 
                "1,484", 
                "654", 
                "691", 
                "1,094", 
                "937", 
                "345", 
                "1,134", 
                "1,318", 
                "2,108", 
                "1,146", 
                "629", 
                "1,534", 
                "251", 
                "364", 
                "548", 
                "289", 
                "1,611", 
                "523", 
                "3,802", 
                "2,089", 
                "147", 
                "2,677", 
                "872", 
                "957", 
                "2,942", 
                "230", 
                "951", 
                "219", 
                "1,540", 
                "5,265", 
                "476", 
                "188", 
                "1,611", 
                "1,649", 
                "475", 
                "1,352", 
                "137"
            ], 
            "x": [
                "Location", 
                "Alabama", 
                "Arizona", 
                "Arkansas", 
                "California", 
                "Colorado", 
                "Connecticut", 
                "Delaware", 
                "District of Columbia", 
                "Florida", 
                "Georgia", 
                "Idaho", 
                "Illinois", 
                "Indiana", 
                "Iowa", 
                "Kansas", 
                "Kentucky", 
                "Louisiana", 
                "Maine", 
                "Maryland", 
                "Massachusetts", 
                "Michigan", 
                "Minnesota", 
                "Mississippi", 
                "Missouri", 
                "Montana", 
                "Nebraska", 
                "Nevada", 
                "New Hampshire", 
                "New Jersey", 
                "New Mexico", 
                "New York", 
                "North Carolina", 
                "North Dakota", 
                "Ohio", 
                "Oklahoma", 
                "Oregon", 
                "Pennsylvania", 
                "Rhode Island", 
                "South Carolina", 
                "South Dakota", 
                "Tennessee", 
                "Texas", 
                "Utah", 
                "Vermont", 
                "Virginia", 
                "Washington", 
                "West Virginia", 
                "Wisconsin", 
                "Wyoming"
            ], 
            "type": "bar", 
            "autobiny": true
        }
    ]
}